stream
{
    log_format  stream_proxy  '$remote_addr - [$time_local] $protocol $status $server_addr - $upstream_addr';

    upstream openldap-server
    {
        server openldap-app-container:1389;
    }
    server
    {
        listen       389;
        listen  [::]:389;
        access_log  /var/log/nginx/access.log  stream_proxy;
        proxy_pass   openldap-server;
    }
    server
    {
        listen       636 ssl;
        listen  [::]:636 ssl;

        include      /work/configs/partial/ssl_certificates.conf;
        ssl_protocols TLSv1.2;

        access_log  /var/log/nginx/access.log  stream_proxy;
        proxy_pass   openldap-server;
    }
}

