map $http_upgrade $connection_upgrade { 
    default upgrade;
    ''      close;
}

include  /work/configs/partial/proxy-log-format.conf;

server {
    listen       80                   default_server;
    listen  [::]:80      ipv6only=on  default_server;
    listen       443 ssl              default_server;
    listen  [::]:443 ssl ipv6only=on  default_server;

    access_log  /var/log/nginx/access.log  proxy;
    include  /work/configs/partial/ssl_certificates.conf;

    location ^~ /certs
    {
         alias  /work/certs/ca;
    }

    location /
    {
        return 421;
    }
}

