
upstream kallithea-server
{
    server kallithea-app-container:5000;
    keepalive 8;
}
server {
    server_name  kallithea.myserver.home;

    include  /work/configs/partial/service-proxy.conf;

    location /
    {
        proxy_pass http://kallithea-server/;
    }
}
