
upstream baget-server
{
    server baget-app-container:80;
    keepalive 8;
}
server {
    server_name  baget.myserver.home;

    include  /work/configs/partial/service-proxy.conf;

    location /
    {
        proxy_pass http://baget-server/;
    }
}
