
upstream bagetter-server
{
    server bagetter-app-container:8080;
    keepalive 8;
}
server {
    server_name  bagetter.myserver.home;

    include  /work/configs/partial/@service-proxy-dual.conf;

    location /
    {
        proxy_pass http://bagetter-server/;
    }
}
