
upstream bookstack-server
{
    server bookstack-app-container:80;
    keepalive 8;
}
server {
    server_name  bookstack.myserver.home;

    include  /work/configs/partial/@service-proxy-https.conf;

    location /
    {
        proxy_pass http://bookstack-server/;
    }
}
server {
    server_name  bookstack.myserver.home;

    include  /work/configs/partial/@redirect-to-https.conf;
}
