
upstream registry-server
{
    server registry-app-container:5000;
    keepalive 8;
}
server {
    server_name  registry.myserver.home images.myserver.home;

    include  /work/configs/partial/service-proxy.conf;

    location /
    {
        client_max_body_size     0;
        proxy_buffering          off;
        proxy_request_buffering  off;
        proxy_pass http://registry-server/;
    }
}

upstream registry-auth-server
{
    server registry-auth-container:5001;
    keepalive 8;
}
server {
    server_name  registry-auth.myserver.home;

    include  /work/configs/partial/service-proxy.conf;

    location /
    {
        proxy_pass http://registry-auth-server/;
    }
}

