
upstream excalidraw-server
{
    server excalidraw-app-container:80;
    keepalive 8;
}
server {
    server_name  excalidraw.myserver.home;

    include  /work/configs/partial/service-proxy.conf;

    location /
    {
        proxy_pass http://excalidraw-server/;
    }
}


upstream excalidraw-room-server
{
    server excalidraw-room-container:80;
    keepalive 8;
}
server {
    server_name  excalidraw-room.myserver.home;

    include  /work/configs/partial/service-proxy.conf;

    location /
    {
        proxy_pass http://excalidraw-room-server/;
    }
}


