
upstream forgejo-server
{
    server forgejo-app-container:3000;
    keepalive 8;
}
server {
    server_name  forgejo.myserver.home;

    include  /work/configs/partial/@service-proxy-dual.conf;

    location /
    {
        proxy_pass http://forgejo-server/;
    }
}
