
upstream it-tools-server
{
    server it-tools-app-container:80;
    keepalive 8;
}
server {
    server_name  it-tools.myserver.home;

    include  /work/configs/partial/@service-proxy-dual.conf;

    location /
    {
        proxy_pass http://it-tools-server/;
    }
}
