
upstream snipe-it-server
{
    server snipe-it-app-container:80;
    keepalive 8;
}
server {
    server_name  snipe-it.myserver.home;

    include  /work/configs/partial/@service-proxy-dual.conf;

    location /
    {
        proxy_pass http://snipe-it-server/;
    }
}
