
upstream snipe-it-server
{
    zone upstream-snipe-it 64k;
    server snipe-it-app-container:80 resolve;
    keepalive 8;
}
server {
    server_name  snipe-it.myserver.home;

    include  /work/configs/partial/@service-proxy-dual.conf;
    include  /work/configs/partial/size-settings-default.conf;

    location /
    {
        proxy_pass http://snipe-it-server/;
    }
}
