
upstream timetagger-server
{
    server timetagger-app-container:80;
    keepalive 8;
}
server {
    server_name  timetagger.myserver.home;

    include  /work/configs/partial/@service-proxy-dual.conf;

    location /
    {

        proxy_pass http://timetagger-server/;
    }
}
