
upstream traggo-server
{
    zone upstream-traggo 64k;
    server traggo-app-container:3030 resolve;
    keepalive 8;
}
server {
    server_name  traggo.myserver.home;

    include  /work/configs/partial/@service-proxy-dual.conf;

    location /
    {
        proxy_pass http://traggo-server/;
    }
}
