
upstream traggo-server
{
    server traggo-app-container:3030;
    keepalive 8;
}
server {
    server_name  traggo.myserver.home;

    include  /work/configs/partial/@service-proxy-dual.conf;

    location /
    {
        proxy_pass http://traggo-server/;
    }
}
