
upstream dillinger-server
{
    zone upstream-dillinger 64k;
    server dillinger-app-container:8080 resolve;
    keepalive 8;
}
server {
    server_name  dillinger.myserver.home;

    include  /work/configs/partial/@service-proxy-dual.conf;
    include  /work/configs/partial/size-settings-default.conf;

    location /
    {
        proxy_pass http://dillinger-server/;
    }
}
