map $http_upgrade $connection_upgrade { 
    default upgrade;
    ''      close;
}

log_format  proxy  '$remote_addr - $remote_user [$time_local] $scheme $http_host "$request" '
                   '$status $body_bytes_sent "$http_referer" '
                   '"$http_user_agent" "$http_x_forwarded_for"';

server {
    listen       80                   default_server;
    listen  [::]:80      ipv6only=on  default_server;
    listen       443 ssl              default_server;
    listen  [::]:443 ssl ipv6only=on  default_server;

    access_log  /var/log/nginx/access.log  proxy;
    include  /work/configs/partial/ssl_certificates.conf;

    location ^~ /certs
    {
         alias  /work/certs/ca;
    }

    location /
    {
        return 421;
    }
}

upstream kallithea-server
{
    server kallithea-app-container:5000;
    keepalive 8;
}
server {
    server_name  kallithea.myserver.home;

    access_log  /var/log/nginx/access.log  proxy;
    include  /work/configs/partial/proxy_server.conf;
    include  /work/configs/partial/size_settings.conf;

    location /
    {
        proxy_pass http://kallithea-server/;
    }
}


upstream baget-server
{
    server baget-app-container:80;
    keepalive 8;
}
server {
    server_name  baget.myserver.home;

    access_log  /var/log/nginx/access.log  proxy;
    include  /work/configs/partial/proxy_server.conf;
    include  /work/configs/partial/size_settings.conf;

    location /
    {
        proxy_pass http://baget-server/;
    }
}


upstream bookstack-server
{
    server bookstack-app-container:80;
    keepalive 8;
}
server {
    server_name  bookstack.myserver.home;

    access_log  /var/log/nginx/access.log  proxy;
    listen       443 ssl;
    listen  [::]:443 ssl;
    include  /work/configs/partial/ssl_certificates.conf;
    include  /work/configs/partial/proxy_settings.conf;

    location /
    {
        proxy_pass http://bookstack-server/;
    }
}
server {
    server_name  bookstack.myserver.home;

    access_log  /var/log/nginx/access.log  proxy;
    listen       80;
    listen  [::]:80;

    return 302 https://$http_host$request_uri;
}


upstream registry-server
{
    server registry-app-container:5000;
    keepalive 8;
}
server {
    server_name  registry.myserver.home images.myserver.home;

    access_log  /var/log/nginx/access.log  proxy;
    include  /work/configs/partial/proxy_server.conf;
    client_max_body_size 0;

    location /
    {
        proxy_pass http://registry-server/;
    }
}


upstream registry-auth-server
{
    server registry-auth-container:5001;
    keepalive 8;
}
server {
    server_name  registry-auth.myserver.home;

    access_log  /var/log/nginx/access.log  proxy;
    include  /work/configs/partial/proxy_server.conf;
    include  /work/configs/partial/size_settings.conf;

    location /
    {
        proxy_pass http://registry-auth-server/;
    }
}


