services:
  app:
    image: registry:2
    restart: unless-stopped
    command: serve /assets/configs/registry-config.yml
    networks:
      composes-frontend:
        aliases:
          - registry-app-container
    volumes:
      - ../../volumes/registry/app/repos:/var/lib/registry
      - ./assets:/assets
    environment:
      - TZ=Asia/Tokyo

  auth:
    image: cesanta/docker_auth:1
    restart: unless-stopped
    command: /assets/configs/auth-config.yml
    networks:
      composes-frontend:
        aliases:
          - registry-auth-container
    volumes:
      - ./assets:/assets
      - ../proxy/assets/certs/ca:/certs
    environment:
      - TZ=Asia/Tokyo

networks:
  composes-frontend:
    external: true
