version: 0.1
log:
  fields:
    service: registry

storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true

http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]

health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3

auth:
  token:
    realm: https://registry-auth.myserver.home/auth
    service: Docker image registry
    issuer: Docker registry auth server
    rootcertbundle: /assets/certs/token-sign.crt
    autoredirect: false
